import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="bg-gradient-to-tr from-gray-700 via-gray-900 to-black min-h-screen overflow-hidden text-white">
				{children}
			</body>
		</html>
	);
}
